### ISSUE TITLE
Ability to set xp cost to less than a full xp per block.

### ISSUE THREAD

**Issue by HighQualityShadows** [ChaoticTrials/Excavar#16]
### Describe your idea

For example 0.1 or 0.25 per block minimum instead of the current 1.

**Comment by MelanX** [comment]
Next time, please add a better description.
This issue can take a bit longer since I have no idea currently, how to do this properly.

**Comment by Randalkobolt** [comment]
Sorry about that. Hopefully Im not causing you too much trouble. I just assumed it wouldn't be very hard to do but now that I think back on it seems like its one of those things that are harder than they should be to code.

**Comment by MelanX** [comment]
Yes, especially because vanilla only stores xp with integers. That excludes values between 0 and 1. I need to combine multiple blocks until it reaches a full number, then remove the xp, and do all the checks.
I also thought about just adding a cost for one excavation task. No matter how many blocks you break, it will always remove the configured amount of xp. Pretty easy to check for this and since I would remove at least one xp each time, it would be something similar as requested.

**Comment by Randalkobolt** [comment]
Yeah, the whole goal here is to use xp cost for vein mining but not have it be too costly. With the current 1 per block broken the first level of xp is  like 4 blocks vein mined which makes it really costly. This all came around because Im trying to be able to release my in development modpack on modrinth as well as curseforge but that requires not using the ftb mods so Im finding alternatives.

**Comment by MelanX** [comment]
Awesome, I definitely support this!
